// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClsXgI1JWst9w1rO1opXTilDzzvRYbg_c',
    appId: '1:771612701805:web:f198de17ba22be972fbb64',
    messagingSenderId: '771612701805',
    projectId: 'sssbiz',
    authDomain: 'sssbiz.firebaseapp.com',
    storageBucket: 'sssbiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG8K-uqruzvJRUg3kxJQSSxTM2zXVdRxo',
    appId: '1:771612701805:android:ca5001e0e76895362fbb64',
    messagingSenderId: '771612701805',
    projectId: 'sssbiz',
    storageBucket: 'sssbiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApD-gXqGo1-xYdnKz-dXRC-vq8D7SoaO8',
    appId: '1:771612701805:ios:3f64aa1928e830aa2fbb64',
    messagingSenderId: '771612701805',
    projectId: 'sssbiz',
    storageBucket: 'sssbiz.appspot.com',
    iosBundleId: 'com.example.backendapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApD-gXqGo1-xYdnKz-dXRC-vq8D7SoaO8',
    appId: '1:771612701805:ios:3f64aa1928e830aa2fbb64',
    messagingSenderId: '771612701805',
    projectId: 'sssbiz',
    storageBucket: 'sssbiz.appspot.com',
    iosBundleId: 'com.example.backendapp',
  );
}
